[package]
name = "tcp_proxy"
version = "0.1.0"
authors = ["mathuis"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
